// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp1;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(HostelDbContext))]
    partial class HostelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp1.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientMiddleName")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ClientSurname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ClientId")
                        .HasName("PK__CLIENT__E67E1A04863F7055");

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("WinFormsApp1.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Login");

                    b.Property<string>("MmiddleName")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MMiddleName");

                    b.Property<string>("Mname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MName");

                    b.Property<string>("Mphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MPhone");

                    b.Property<string>("Msurname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MSurname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Password");

                    b.HasKey("ManagerId")
                        .HasName("PK__MANAGER__3BA2AA81B25F7CAF");

                    b.ToTable("MANAGER", (string)null);
                });

            modelBuilder.Entity("WinFormsApp1.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BedQty")
                        .HasColumnType("int")
                        .HasColumnName("BedQTY");

                    b.Property<int>("FreeBedQty")
                        .HasColumnType("int")
                        .HasColumnName("FreeBedQTY");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("RoomId")
                        .HasName("PK__ROOM__328639197DFBF754");

                    b.ToTable("ROOM", (string)null);
                });

            modelBuilder.Entity("WinFormsApp1.Zaselenie", b =>
                {
                    b.Property<int>("ZaselenieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZaselenieID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaselenieId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<DateTime>("DataVisel")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataZasel")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.HasKey("ZaselenieId")
                        .HasName("PK__ZASELENI__3800D253729AD88B");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.ToTable("ZASELENIE", (string)null);
                });

            modelBuilder.Entity("WinFormsApp1.Zaselenie", b =>
                {
                    b.HasOne("WinFormsApp1.Client", "Client")
                        .WithMany("Zaselenies")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK__ZASELENIE__Clien__286302EC");

                    b.HasOne("WinFormsApp1.Room", "Room")
                        .WithMany("Zaselenies")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__ZASELENIE__RoomI__29572725");

                    b.Navigation("Client");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WinFormsApp1.Client", b =>
                {
                    b.Navigation("Zaselenies");
                });

            modelBuilder.Entity("WinFormsApp1.Room", b =>
                {
                    b.Navigation("Zaselenies");
                });
#pragma warning restore 612, 618
        }
    }
}
